# Generated by Django 4.1.7 on 2023-03-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='PhotoFilename',
            new_name='PhotoFileName',
        ),
    ]
